# Generated by Django 3.1.4 on 2020-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('聊天機器人', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_bmr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
