# Generated by Django 3.1.4 on 2020-12-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('聊天機器人', '0002_user_info_user_bmr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='mdt',
        ),
        migrations.AddField(
            model_name='user_info',
            name='cal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user_info',
            name='data_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user_info',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='food',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user_info',
            name='period',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_bmr',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
