# Generated by Django 3.1.4 on 2020-12-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('聊天機器人', '0003_auto_20201213_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
